### ISSUE TITLE
fade towards hl-line color

### ISSUE THREAD

**Issue by Dickby** [protesilaos/pulsar#1]
Hi Prot, 
first of all, thanks for your work, i use several of your packages and I am really happy with them.
I know that pulsar is meant for finding the cursor faster after window/cursor movements.
I use it together with `hl-line-mode` which is a bit redundant i guess, but i like it.
My question is, if it would be possible to add an option to pulsar that lets the pulse color shift to the hl-line color instead of 
the buffer background color?
What do you think?
Thanks

**Comment by protesilaos** [comment]
> Hi Prot, 

Hello there!

> first of all, thanks for your work, i use several of your packages and
> I am really happy with them.

You are welcome!

> I know that pulsar is meant for finding the cursor faster after
> window/cursor movements.  I use it together with `hl-line-mode` which
> is a bit redundant i guess, but i like it.

I also use this combination: in Dired, for example.

> My question is, if it would be possible to add an option to pulsar
> that lets the pulse color shift to the hl-line color instead of the
> buffer background color?  What do you think?

I don't remember the technicalities right now.  Will take a look, do
some tests, and report back to you later in the day.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by protesilaos** [comment]
It works if we make a change to pulse.el:

```elisp
(defun pulse-momentary-highlight-overlay (o &optional face)
  "Pulse the overlay O, unhighlighting before next command.
Optional argument FACE specifies the face to do the highlighting."
  ;; We don't support simultaneous highlightings.
  (pulse-momentary-unhighlight)
  (overlay-put o 'original-face (overlay-get o 'face))
  ;; Make this overlay take priority over the `transient-mark-mode'
  ;; overlay.
  (overlay-put o 'original-priority (overlay-get o 'priority))
  (overlay-put o 'priority 1)
  (setq pulse-momentary-overlay o)
  (if (eq pulse-flag 'never)
      nil
    (if (or (not pulse-flag) (not (pulse-available-p)))
	;; Provide a face... clear on next command
	(progn
	  (overlay-put o 'face (or face 'pulse-highlight-start-face))
	  (add-hook 'pre-command-hook
		    #'pulse-momentary-unhighlight))
      ;; Pulse it.
      (overlay-put o 'face 'pulse-highlight-face)
      ;; The pulse function puts FACE onto 'pulse-highlight-face.
      ;; Thus above we put our face on the overlay, but pulse
      ;; with a reference face needed for the color.
      (pulse-reset-face face)
      (let* ((start (color-name-to-rgb
                     (face-background 'pulse-highlight-face nil 'default)))
             (stop (color-name-to-rgb (face-background hl-line-face nil 'default))) ; I changed this
             (colors (mapcar (apply-partially 'apply 'color-rgb-to-hex)
                             (color-gradient start stop pulse-iterations))))
        (setq pulse-momentary-timer
              (run-with-timer 0 pulse-delay #'pulse-tick
                              colors
                              (time-add nil
                                        (* pulse-delay pulse-iterations))))))))
```

Though this is the sort of thing that is better done in emacs.git by introducing a new `pulse-highlight-end-face`.  Then pulsar or the user can simply use that face.  Thus:

```diff
 lisp/cedet/pulse.el | 7 ++++++-
 1 file changed, 6 insertions(+), 1 deletion(-)

diff --git a/lisp/cedet/pulse.el b/lisp/cedet/pulse.el
index f7af10887c..54b7845423 100644
--- a/lisp/cedet/pulse.el
+++ b/lisp/cedet/pulse.el
@@ -81,6 +81,11 @@ (defface pulse-highlight-start-face
   "Face used at beginning of a highlight."
   :group 'pulse)
 
+(defface pulse-highlight-end-face nil
+  "Face whose background is used at the end of a highlight."
+  :group 'pulse
+  :version "29.1")
+
 (defface pulse-highlight-face
   '((((class color) (background dark))
      (:background "#AAAA33"))
@@ -154,7 +159,7 @@ (defun pulse-momentary-highlight-overlay (o &optional face)
       (pulse-reset-face face)
       (let* ((start (color-name-to-rgb
                      (face-background 'pulse-highlight-face nil 'default)))
-             (stop (color-name-to-rgb (face-background 'default)))
+             (stop (color-name-to-rgb (face-background 'pulse-highlight-end-face nil 'default)))
              (colors (mapcar (apply-partially 'apply 'color-rgb-to-hex)
                              (color-gradient start stop pulse-iterations))))
         (setq pulse-momentary-timer
```

What do you think?

**Comment by Dickby** [comment]
Beautiful!
I don't know how those emacs core people think about that change in pulse.el, but 
if the INHERIT argument of face-backgrround is set to default as you did, it shouldn't bother anybody who doesn't want to use that functionality.
Anyways until then i will use your modified `pulse-momentary-highlight-overlay`.
Thanks a lot.

**Comment by protesilaos** [comment]
> Anyways until then i will use your modified `pulse-momentary-highlight-overlay`.
> Thanks a lot.

You are welcome!

-- 
Protesilaos Stavrou
https://protesilaos.com
