### ISSUE TITLE
Feature Request: Add mode to pulse yanked text 

### ISSUE THREAD

**Issue by AnweshGangula** [protesilaos/pulsar#10]
I recently found [this article](https://blog.meain.io/2020/emacs-highlight-yanked) which talks about using [Pulse Region](https://www.emacswiki.org/emacs/PulseRegion) to highlight yanked text. But I'm not able to figure out to use in my current configuration.

I would like it if this can be implemented in pulsar.el

___
Check out a demo from the video
![highlight yanked text](https://github.com/protesilaos/pulsar/assets/22996896/851c8e10-9b9a-4f2e-ac4a-efaf836ae7c3)

**Comment by protesilaos** [comment]
> From: Anwesh Gangula ***@***.***>
> Date: Wed, 19 Jun 2024 08:11:40 -0700
>
> Check out a demo from the video
> ![highlight yanked text](https://github.com/protesilaos/pulsar/assets/22996896/851c8e10-9b9a-4f2e-ac4a-efaf836ae7c3)

We can easily make pulsar produce a pulse after a command. For example,
evaluate this:

    (add-to-list 'kill-ring-save 'pulsar-pulse-functions)

Then, every time you use the command 'kill-ring-save' (M-w by default),
you will see pulse afterwards.

The problem, however, is that we always pulse the whole line. Whereas I
think we need to only operate on the given region. I believe this will
not be as straightforward, because we will need our pulse effect to know
the region boundaries of the previous command.

Unless, we maintain a list of known commands and then we write wrapper
functions to filter them, get their region boundaries, call them as
intended, and then use the data we got to produce the right pulse. This
is a deviation from the simpler approach we have right now, but maybe it
is worth trying.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by AnweshGangula** [comment]
I found the source code of the origin pulse.el in [this link](https://fossies.org/linux/emacs/lisp/cedet/pulse.el). Would it to be simpler to replicate the same behavior using the same code?

**Comment by d1egoaz** [comment]
FYI there is a tool https://github.com/edkolev/evil-goggles/ to accomplish what @AnweshGangula is requesting. I use evil-goggles and pulsar combined.

**Comment by protesilaos** [comment]
> From: Diego Alvarez ***@***.***>
> Date: Fri, 21 Jun 2024 14:55:49 -0700
>
> FYI there is a tool https://github.com/edkolev/evil-goggles/ to
> accomplish what @AnweshGangula is requesting. I use evil-goggles and
> pulsar combined.

Thank you! This reminded me that we also have the goggles package for
those who do not use Evil: <https://github.com/minad/goggles>.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by AnweshGangula** [comment]
Thank you for sharing this these packages, I will look into it.

**Comment by d1egoaz** [comment]
- evil-googles, only with evil-mode.
- goggles, "This library is the holy counterpart of evil-goggles."

**Comment by Daskeladden** [comment]
Maybe this?

```emacs-lisp
  (advice-add 'kill-ring-save :after
              (lambda (beg end &optional region)
                (pulsar-pulse-region))))
```

**Comment by protesilaos** [comment]
> From: Ronny Randen ***@***.***>
> Date: Fri, 30 Aug 2024 01:25:44 -0700
>
> Maybe this?
>
> ```emacs-lisp
>   (advice-add 'kill-ring-save :after
>               (lambda (beg end &optional region)
>                 (pulsar-pulse-region))))
> ```

This should work. The next step is to make sure we do the same for the
paste as well. Anything else that is relevant should be covered in the
same way.

I have no strong opinion about this. If people want it, then we can have
the mode. Even though goggles.el already exists, I understand why people
may prefer to only use one package.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by shipmints** [comment]
I was able to hack in naive region pulsing with a couple of lines of code. The idea would be to have a ```pulsar-pulse-region-functions``` list and pulse the region. This seems to work as a prototype (with only simple, non-exhaustive testing; e.g., I didn't try it on a rectangle).

For people that also use ```googles```, they would simply leave the region functions list empty.

I don't use ```vi``` emulation modes but it seems to me those commands should also work fine. I'd be happy to test with at least one ```vi``` mode (```meow``` or ```evil```, I guess). 

```elisp
(defun pulsar--post-command-pulse ()
  "Run `pulsar-pulse-line' for `pulsar-pulse-functions'."
  (when (or pulsar-mode pulsar-global-mode)
    (cond
     ((or (memq this-command pulsar-pulse-functions)
          (memq real-this-command pulsar-pulse-functions))
      (pulsar-pulse-line))
     ;; This would be `pulsar-pulse-region-functions'
     ((memq this-command '(yank kill-region kill-ring-save append-next-kill undo))
      (pulsar--pulse nil nil (mark) (point))))))
```

**Comment by shipmints** [comment]
Give this branch a try and see how it works for you.

https://github.com/shipmints/pulsar/tree/pulse-region-commands

**Comment by shipmints** [comment]
Has anyone given this a try? Any suggestions for refinement?

**Comment by protesilaos** [comment]
@shipmints I have not had a chance to check it out. I have been busy these past few days. I expect to have more time next week.

**Comment by shipmints** [comment]
Anyone taken a look yet?

**Comment by protesilaos** [comment]
@shipmints I replied in [the other thread](https://github.com/protesilaos/pulsar/issues/18). Thank you!

**Comment by shipmints** [comment]
This is now handled via #18

**Comment by protesilaos** [comment]
Thank you @shipmints! We can safely close this issue now. If anyone has any further comments, you are welcome to share them.
