### ISSUE TITLE
Consider support for window-state-change-hook in addition to commands (which can be left empty)

### ISSUE THREAD

**Issue by shipmints** [protesilaos/pulsar#18]
Per this discussion:

https://www.reddit.com/r/emacs/comments/1fvffs8/pulsicel_temporarily_highlight_the_current_line/

I have not had issues with pulse.el being laggy.

**Comment by protesilaos** [comment]
> From: shipmints ***@***.***>
> Date: Sat,  5 Oct 2024 09:35:59 -0700
>
> Per this discussion:
>
> https://www.reddit.com/r/emacs/comments/1fvffs8/pulsicel_temporarily_highlight_the_current_line/

I have not read that thread yet. Just commenting on the title of your
issue.

We were using that hook before. Switch to version 0.4.0 and then search
for pulsar-pulse-on-window-change. It was buggier than what we have now,
though I forgot the details. I deprecated in version 0.5.0.

> I have not had issues with pulse.el being laggy.

I have not experienced this. Maybe there is a bug for it on the Emacs tracker?

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by shipmints** [comment]
Looks like 0.4.0 was ```window-selection-change-functions``` not ```window-state-change-hook``` but perhaps previous experiments used state change over selection change.

**Comment by protesilaos** [comment]
> From: shipmints ***@***.***>
> Date: Sun,  6 Oct 2024 07:36:19 -0700
>
> Looks like 0.4.0 was ```window-selection-change-functions``` not
> ```window-state-change-hook``` but perhaps previous experiments used
> state change over selection change.

Oh, I see. My mistake then! I have no principled objection to it. It
looks promising and I am curious to learn more. I wonder what the effect
will be on what we currently have. Do you think we should provide this
in addition to what we offer or as an alternative to it?

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by shipmints** [comment]
Anyone taken a look yet?

**Comment by protesilaos** [comment]
> From: shipmints ***@***.***>
> Date: Tue, 15 Oct 2024 16:26:39 -0700
>
> Anyone taken a look yet?

No, I am sorry. Things have been much busier than I had anticipated. My
next available day is this Sunday.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by protesilaos** [comment]
I am trying your code now. Okay for the "pulse region" code.

About the function added to `window-state-change-functions` do you think we need this in addition to the `post-command-hook`? Or should be it an "or" logic, perhaps with some user option involved or some Do-What-I-Mean kind of behaviour (e.g. `pulsar-pulse-functions` is nil)?

**Comment by shipmints** [comment]
I think in addition makes the most sense. Documentation can guide people to choose one or the other or both as they see fit (vs preventing both which is what "or" logic would suggest). We can make the window change hook the default behavior and leave the functions list nil.

On pulse region, when mark is far away from point, it does flash more of the screen than people might expect. Not that there is much we can do. One suggestion, though, is that for region pulses, I wonder if an alternate color scheme makes sense to differentiate line pulses from region pulses.

**Comment by protesilaos** [comment]
> From: shipmints ***@***.***>
> Date: Sun, 20 Oct 2024 05:24:58 -0700
>
> I think in addition makes the most sense. Documentation can guide
> people to choose one or the other or both as they see fit (vs
> preventing both which is what "or" logic would suggest). We can make
> the window change hook the default behavior and leave the functions
> list nil.

Fine, let's have both and we see if we need to make any further changes
down the road.

> On pulse region, when mark is far away from point, it does flash more
> of the screen than people might expect. Not that there is much we can
> do. One suggestion, though, is that for region pulses, I wonder if an
> alternate color scheme makes sense to differentiate line pulses from
> region pulses.

I had a plan to add a pulsar-region-face, which is analogous to the
pulsar-face. This, at least, gives the user the option to have something
different there. About the level of intensity though, this is more
tricky because we do not know how big the region is or if there is any
background there already (e.g. pulsing over a diff). I guess we can find
that and use an appropriate background, but maybe that is too
complicated and error-prone. At any rate, I am open to whatever you
think is best.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by shipmints** [comment]
A customizable region face is the best idea. It can default to the same as pulsar-face to start, I'd think. People can customize as they see fit.

**Comment by protesilaos** [comment]
> From: shipmints ***@***.***>
> Date: Sun, 20 Oct 2024 06:35:45 -0700
>
> A customizable region face is the best idea. It can default to the
> same as pulsar-face to start, I'd think. People can customize as they
> see fit.

Yes, this is what I was thinking as well.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by shipmints** [comment]
I've been running my branch with pulsar-pulse-on-window-change t, pulsar-pulse-functions nil and it works well and is simple and retains the command/alias option should it be necessary for some cases.

pulsar-pulse-region-functions set to
        '(yank
          kill-region
          kill-ring-save
          append-next-kill
          undo))
seems okay.

Would you prefer if I added the pulse region face in my branch and submit a pull request? Anything else you'd like to see?

**Comment by protesilaos** [comment]
I merged the PR, so I think we can safely close this. Thank you!

**Comment by shipmints** [comment]
#10 is also covered here so feel free to close #10 also.

**Comment by protesilaos** [comment]
Indeed, I forgot to close that one.
