### ISSUE TITLE
Performance issues with `pulsar-pulse-on-window-change`

### ISSUE THREAD

**Issue by protesilaos** [protesilaos/pulsar#21]
Hello @shipmints. I have noticed a degraded performance when I am using Pulsar with the new user option you added. I am thinking of adding something like this, but am concerned it will still be a performance penalty:

```diff
 pulsar.el | 2 ++
 1 file changed, 2 insertions(+)

diff --git a/pulsar.el b/pulsar.el
index 985240f..bbdf81a 100644
--- a/pulsar.el
+++ b/pulsar.el
@@ -519,6 +519,8 @@ (defun pulsar--pulse-on-window-change (&rest _)
   "Run `pulsar-pulse-line' on window change."
   (when (and pulsar-pulse-on-window-change
              (not (minibufferp))
+             (not (pulsar--this-command-in-functions-p pulsar-pulse-functions))
+             (not (pulsar--this-command-in-functions-p pulsar-pulse-region-functions))
              (or pulsar-mode pulsar-global-mode))
     (pulsar-pulse-line)))
 
```

The idea is to check when we are pulsing so that we do not do it two or more times (so this kind of change may need to be applied elsewhere, but am sharing this to get the discussion going).

**Comment by shipmints** [comment]
As a defensive measure for people who may configure both command list and the window change hook, it seems like a good idea. I've been running with an empty list.

**Comment by protesilaos** [comment]
> From: Abdelhak Bougouffa ***@***.***>
> Date: Mon, 18 Nov 2024 15:48:14 -0800

> [... 5 lines elided]

> I think hooking the function to `window-selection-change-functions` is
> more appropriate than `window-state-change-functions`.

I also think that it pulses too much now, but need to test it further.
Note that in older versions of Pulsar I had tried the 'window-selection-change-functions'
and eventually removed it. I do not remember what the problem was, but
maybe I just missed something obvious. With input from you, shipmints,
or anyone else, I am happy to have this done the correct way.

> For me, this fixed the issue (as I can observe it for now):
>
> ```elisp
> (advice-add
>  'pulsar-mode :after
>  (lambda +pulsar--fix-pulse-on-window-change:after-a (&rest _args)
>    (if pulsar-mode
>        (progn
>          (remove-hook 'window-state-change-functions #'pulsar--pulse-on-window-change 'local)
>          (when pulsar-pulse-on-window-change
>            (add-hook 'window-selection-change-functions #'pulsar--pulse-on-window-change nil 'local)))
>      (remove-hook 'window-selection-change-functions #'pulsar--pulse-on-window-change 'local))))
> ```

Fine. Let's find a setup that works for everybody and provide the
relevant user options, so there is no need for such changes.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by shipmints** [comment]
I have been using pulsar with pulsar-pulse-on-window-change and an empty pulsar-pulse-functions list and have only good experience with no performance issues and pulsing at appropriate and opportune times.

Can y'all be more precise about what performance issues you observe?

**Comment by abougouffa** [comment]
Hi again @shipmints 

Thank you for your reactiveness!

I've tried the new branch. It is much better now, but still a bit annoying to my taste.

Also, if you do:

```elisp
(advice-add 'pulsar--pulse :after (lambda (&rest _a) (message "CALLED from %S!" (get-buffer-window))))
```

You will see that at each event, the `pulsar--pulse` gets called twice instead of once!

**Comment by shipmints** [comment]
No problem. I use this every day, too.

I don't see the same flashing when searching that you do. Are you using off-the-shelf isearch or some other package(s) that add functionality that it would be good to be aware of?

**Comment by abougouffa** [comment]
I've checked, the `isearch` issue was apparently caused by a third party package named `isearch-mb` which I had enabled but never used!

However, can you check this in your setup please?

> Also, if you do:
> 
> ```elisp
> (advice-add 'pulsar--pulse :after (lambda (&rest _a) (message "CALLED from %S!" (get-buffer-window))))
> ```
> 
> You will see that at each event, the `pulsar--pulse` gets called twice instead of once!

**Comment by protesilaos** [comment]
> From: Abdelhak Bougouffa ***@***.***>
> Date: Wed, 20 Nov 2024 16:46:56 -0800
>
> I've checked, the `isearch` issue was apparently caused by a third
> party package named `isearch-mb` which I had enabled but never used!
>
> However, can you check this in your setup please?
>
>> Also, if you do:
>> 
>> ```elisp
>> (advice-add 'pulsar--pulse :after (lambda (&rest _a) (message "CALLED from %S!" (get-buffer-window))))
>> ```
>> 
>> You will see that at each event, the `pulsar--pulse` gets called twice instead of once!

While waiting for this, I am interested on the "annoying" part you
mentioned earlier. Users may prefer to set things one way or another. I
think to have the least intrusive experience, we should set the new user
option 'pulsar-pulse-on-window-change' to nil by default. This way, the
package will work the same for existing users and those who want to try
the new approach will know what they are opting in to.

Same principle for the region pulsing, though that may be best served
via a new minor mode: 'pulsar-region-mode' and its global variant.

What do you think?

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by abougouffa** [comment]
Hi @protesilaos 

> Users may prefer to set things one way or another. I
think to have the least intrusive experience, we should set the new user
option 'pulsar-pulse-on-window-change' to nil by default. This way, the
package will work the same for existing users and those who want to try
the new approach will know what they are opting in to.

Totally agree!

@shipmints 
I'm using this config for now and it is working Ok. I still have the double triggering issue that I mentioned above:

> Also, if you do:
> 
> ```emacs-lisp
> (advice-add 'pulsar--pulse :after (lambda (&rest _a) (message "CALLED from %S!" (get-buffer-window))))
> ```
> 
> You will see that at each event, the `pulsar--pulse` gets called twice instead of once!

I suggest to do this change in `pulsar--pulse-on-window-change` to trigger a line pulse only from the right window (as I said, triggering `pulsar-pulse-line` from **any** window will cause the pulse to be done on the **selected** window, so there is no need to do it unless we are in the right window):

```diff
-(defun pulsar--pulse-on-window-change (&rest _)
-  "Run `pulsar-pulse-line' on window change."
+(defun pulsar--pulse-on-window-change (window)
+  "Run `pulsar-pulse-line' on WINDOW change."
   (when (and pulsar-pulse-on-window-change
+             (eq (frame-selected-window) window)
              (not (minibufferp))
              ;; Avoid double pulsing when both
              ;; pulsar-pulse-on-window-change and
              ;; pulsar-pulse-functions are in effect.
              (not (memq this-command pulsar-pulse-functions))
              (not (memq real-this-command pulsar-pulse-functions))
              (or pulsar-mode pulsar-global-mode))
     (pulsar-pulse-line)))
```

With this change, `pulsar-pulse-line` will be called only once on window events.

**Comment by shipmints** [comment]
@abougouffa that's a good change. I've added it to the branch. Also see #22 for the interactive test that may also be of interest to help assess.
