### ISSUE TITLE
Consider adding dired support

### ISSUE THREAD

**Issue by orontee** [protesilaos/pulsar#26]
Thank you for this package!

I found that adding the following functions to `pulsar-pulse-functions` greatly improves navigability in dired buffers:
- `dired-maybe-insert-subdir`
- `dired-up-directory`
- `dired-goto-file`
- `dired-next-dirline`
- `dired-prev-dirline`

**Comment by protesilaos** [comment]
> From: Matthias Meulien ***@***.***>
> Date: Tue, 17 Dec 2024 15:21:28 -0800
>
> Thank you for this package!

You are welcome!

> I found that adding the following functions to `pulsar-pulse-functions` greatly improves navigability in dired buffers:
> - `dired-maybe-insert-subdir`
> - `dired-up-directory`
> - `dired-goto-file`
> - `dired-next-dirline`
> - `dired-prev-dirline`

Good idea! I just added them.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by orontee** [comment]
Not related to dired and not found much time to test but `next-error-recenter`, `next-error`, `previous-error` make sense too.

**Comment by protesilaos** [comment]
> From: Matthias Meulien ***@***.***>
> Date: Wed, 18 Dec 2024 08:13:06 -0800
>
> Not related to dired and not found much time to test but `next-error-recenter`, `next-error`, `previous-error` make sense too.

I have not checked again, though I have a vague memory that those would
already do some pulsing. Can you check?

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by protesilaos** [comment]
> From: Matthias Meulien ***@***.***>
> Date: Wed, 18 Dec 2024 08:31:57 -0800
>
> Last but not least: `imenu`.

Done!

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by orontee** [comment]
> From: Matthias Meulien ***@***.***> Date: Wed, 18 Dec 2024 08:13:06 -0800 Not related to dired and not found much time to test but `next-error-recenter`, `next-error`, `previous-error` make sense too.
> I have not checked again, though I have a vague memory that those would already do some pulsing. Can you check?
> […](#)
> -- Protesilaos Stavrou https://protesilaos.com

No, I just checked, they don't.

**Comment by protesilaos** [comment]
> From: Matthias Meulien ***@***.***>
> Date: Fri, 20 Dec 2024 12:55:48 -0800
>
> `occur-mode-goto-occurrence` is a good candidate too.

I just added this one and the others you suggested. Thank you!

-- 
Protesilaos Stavrou
https://protesilaos.com
