### ISSUE TITLE
Does it make sense to have pulses in buffers with Hl-Line Mode enabled?

### ISSUE THREAD

**Issue by orontee** [protesilaos/pulsar#27]
I am an heavy user of Hl-Line Mode: I enable this minor mode in all modes derivating from `tabulated-list-mode`, 
`bookmark-bmenu-mode`, `log-view-mode`, `xref--xref-buffer-mode`, etc.

The visual effect when combined with pulsar pulses is not that nice. Maybe an equivalent of the following could be added to the package?

```
  (defun pulsar--on ()
  "Enable `pulsar-mode'."
  (unless (or pulsar-mode
	      (and (boundp 'hl-line-mode) hl-line-mode)             ;; This disable pulses when hl-line minor mode is enabled
              (minibufferp)
              (and pulsar-inhibit-hidden-buffers (string-prefix-p " " (buffer-name))))
    (let (inhibit-quit)
      (pulsar-mode 1))))
```

**Comment by protesilaos** [comment]
> From: Matthias Meulien ***@***.***>
> Date: Tue, 17 Dec 2024 15:28:33 -0800
>
> I am an heavy user of Hl-Line Mode: I enable this minor mode in all modes derivating from `tabulated-list-mode`, 
> `bookmark-bmenu-mode`, `log-view-mode`, `xref--xref-buffer-mode`, etc.
>
> The visual effect when combined with pulsar pulses is not that nice. Maybe an equivalent of the following could be added to the package?
>
> ```
>   (defun pulsar--on ()
>   "Enable `pulsar-mode'."
>   (unless (or pulsar-mode
> 	      (and (boundp 'hl-line-mode) hl-line-mode)             ;; This disable pulses when hl-line minor mode is enabled
>               (minibufferp)
>               (and pulsar-inhibit-hidden-buffers (string-prefix-p " " (buffer-name))))
>     (let (inhibit-quit)
>       (pulsar-mode 1))))
> ```

I think this makes sense as a user option. But intstead of a boolean, it
may be better to accept a list of modes. If any of those is enabled in
the current buffer, then Pulsar will not produce a pulse.

This granted, I think we should not handle it in the function you
specify. The mode should be enabled in all regular buffers, because this
is what the user asked (otherwise, the user will do (pulsar-mode -1) via
the relevant hook).

What do you think?

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by orontee** [comment]
> What do you think?

I started using:
```
  (add-hook 'hl-line-mode-hook
	    (lambda () (pulsar-mode -1)))
```
and I am convinced it's the right thing to do. I can live with this, feel free to close the issue.

**Comment by protesilaos** [comment]
> From: Matthias Meulien ***@***.***>
> Date: Wed, 18 Dec 2024 08:16:27 -0800
>
>> What do you think?
>
> I started using:
> ```
>   (add-hook 'hl-line-mode-hook
> 	    (lambda () (pulsar-mode -1)))
> ```
> and I am convinced it's the right thing to do. I can live with this, I close the issue.

Very well!

-- 
Protesilaos Stavrou
https://protesilaos.com
