### ISSUE TITLE
Don't pulse in minibuffer?

### ISSUE THREAD

**Issue by djl** [protesilaos/pulsar#3]
Would it be possible to add an option to disable pulsing in the minibuffer? It seems like anything that uses `read-file-name` or the like (e.g. `find-files`) causes a pulse. This feels unnecessary as these types of functions always open the minibuffer, which is usually static.

Thanks!

**Comment by protesilaos** [comment]
Hello @djl!  I was already thinking about this change I did in commit `a35413a`.

Can you give it a try?  Does it solve your problem?

**Comment by djl** [comment]
Yep. a35413a totally fixed my issue.

Thanks again!

**Comment by protesilaos** [comment]
You are welcome!

Closing now.
