### ISSUE TITLE
does not pulse in `(other-window -1)`

### ISSUE THREAD

**Issue by mmahmoudian** [protesilaos/pulsar#7]
Thanks Prot, I've been using Pulsar for months and it is great.

Today I was making a keybinding for `(other-window -1)` to do what `C-x o` does but in reverse, that I realized the pulsing does not happen when `count` is set to `-1`. I checked in `pulsar-pulse-functions` to see if `other-window` is natively supported on I manually added it, and it is actually there and pulsar works just fine when going forward, but not backwards.

For you convenience, here is the binding:

```el
(global-set-key
 (kbd "C-x O")
 (lambda ()
   (interactive)
   (other-window -1)))
```

**Comment by protesilaos** [comment]
> From: Mehrad Mahmoudian ***@***.***>
> Date: Wed, 17 Jan 2024 05:24:46 -0800
>
> Thanks Prot, I've been using Pulsar for months and it is great.

You are welcome!

> Today I was making a keybinding for `(other-window -1)` to do what
> `C-x o` does but in reverse, that I realized the pulsing does not
> happen when `count` is set to `-1`. I checked in
> `pulsar-pulse-functions` to see if `other-window` is natively
> supported on I manually added it, and it is actually there and pulsar
> works just fine when going forward, but not backwards.
>
> For you convenience, here is the binding:
>
> ```el
> (global-set-key
>  (kbd "C-x O")
>  (lambda ()
>    (interactive)
>    (other-window -1)))
> ```

What if you add this after the call to 'other-window'?

    (setq this-command 'other-window)

Thus:

    (global-set-key
     (kbd "C-x O")
     (lambda ()
       (interactive)
       (other-window -1)
       (setq this-command 'other-window)))

That way, Emacs will say that the command you called is 'other-window'
instead of the lambda it now returns.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by mmahmoudian** [comment]
Thanks, this works perfectly. Now I learnt a new thing.

So to be clear, this is actually not a Pulsar bug, but rather my "bug" in understanding how the pulsar hooks to aftermath of `other-window` ?

**Comment by protesilaos** [comment]
> From: Mehrad Mahmoudian ***@***.***>
> Date: Sat, 20 Jan 2024 15:05:03 -0800
>
> Thanks, this works perfectly. Now I learnt a new thing.

You are welcome!

> So to be clear, this is actually not a Pulsar bug, but rather my "bug"
> in understanding how the pulsar hooks to aftermath of `other-window` ?

Pulsar arranges to run right after a given command. This is basically
done by asking Emacs which was the 'last-command'. In your case, the
'last-command' was not 'other-window' but the lambda. So we needed to
explicitly tell Emacs that what we actuall do with 'this-command' is
'other-window'.

-- 
Protesilaos Stavrou
https://protesilaos.com
