### ISSUE TITLE
Pulse on focus follows mouse?

### ISSUE THREAD

**Issue by 99702** [protesilaos/pulsar#8]
Hello prot,

I've enabled,  focus follows mouse, to automatically select different frames on hovering. For this case, i cant get pulse.
``
(setq focus-follows-mouse t)
``

How can i enable in hovering too?

Thank you for your answer.

**Comment by protesilaos** [comment]
> From: Rajan ***@***.***>
> Date: Wed, 27 Mar 2024 23:16:27 -0700
>
> Hello prot,

Hello there!

> I've enabled,  focus follows mouse, to automatically select different frames on hovering. For this case, i cant get pulse.
> ``
> (setq focus-follows-mouse t)
> ``
>
> How can i enable in hovering too?
>
> Thank you for your answer. 

Does it work if you add handle-select-window to the pulsar-pulse-functions?

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by 99702** [comment]
> handle-select-window

yes it works now. Thank you.
