### ISSUE TITLE
Pulsar behaves differently when switching frames

### ISSUE THREAD

**Issue by ashlineldridge** [protesilaos/pulsar#9]
Hi @protesilaos, thanks for another great package. It seems as though Pulsar behaves differently for commands that cause point to move between frames as opposed to commands that keep point within the current frame. This can be exaggerated with the following settings:

```elisp
(setq pulsar-iterations 25)
(add-to-list 'pulsar-pulse-functions 'avy-goto-line)
```

If I use `avy-goto-line` to jump to a line in the same frame, Pulsar will show a nice long pulse. However, if I use the same command to jump to a line in another frame, I get a short abbreviated pulse - as though the `25` isn't be respected.

I'm currently using Emacs 29.3.

Any idea what could be causing this? AFAIK, I don't have any special configuration that could be interfering with this.

Thanks!

**Comment by ashlineldridge** [comment]
Closing as with Emacs 30.0.60 and the latest version of Pulsar this is no longer an issue for me.

**Comment by protesilaos** [comment]
> From: Ashlin Eldridge ***@***.***>
> Date: Wed, 28 Aug 2024 23:53:50 -0700
>
> Closing as with Emacs 30.0.60 and the latest version of Pulsar this is no longer an issue for me.

Interesting! I am curious what has changed. But it is okay now.

-- 
Protesilaos Stavrou
https://protesilaos.com
